apiVersion: v1
kind: Service
metadata:
  name: tetrips-service
  labels:
    app: tetrips-service
spec:
  type: LoadBalancer
  ports:
    - name: gateway
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: eureka
      protocol: TCP
      port: 8761
      targetPort: 8761
    - name: user
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: tetrips